"""Composition root — façade DI."""

from __future__ import annotations

from e_learning.presentation.api.dependencies.catalog import (
    get_create_chapter,
    get_create_document,
    get_create_formation,
    get_create_video,
    get_delete_chapter,
    get_delete_document,
    get_delete_formation,
    get_delete_video,
    get_get_document_path,
    get_get_formation,
    get_get_video_path,
    get_list_chapter_documents,
    get_list_formations,
    get_move_video,
    get_reconcile_catalog,
    get_rename_chapter,
    get_rename_formation,
    get_rename_video,
    get_reorder_chapters,
    get_reorder_videos,
    get_start_media_conversion,
    get_update_document,
)
from e_learning.presentation.api.dependencies.content import (
    get_ask_formation,
    get_generate_summary,
    get_get_summary,
    get_get_transcription,
    get_index_formation,
    get_start_formation_index,
    get_start_summary_generation,
    get_start_transcription,
    get_update_summary,
)
from e_learning.presentation.api.dependencies.learning import (
    get_create_note,
    get_delete_note,
    get_get_formation_progress,
    get_get_progress,
    get_list_formations_progress,
    get_list_notes,
    get_update_note,
    get_upsert_progress,
)
from e_learning.presentation.api.dependencies.repositories import (
    ChapterRepositoryDep,
    DocumentRepositoryDep,
    FormationRepositoryDep,
    NoteRepositoryDep,
    ProgressRepositoryDep,
    UserRepositoryDep,
    VideoRepositoryDep,
)
from e_learning.presentation.api.dependencies.session import SessionDep, get_session
from e_learning.presentation.api.dependencies.storage import (
    CatalogStorageDep,
    MediaFilesDep,
)
from e_learning.presentation.api.dependencies.user import get_generate_user, get_restore_user

__all__ = [
    "SessionDep",
    "get_session",
    "UserRepositoryDep",
    "FormationRepositoryDep",
    "ChapterRepositoryDep",
    "VideoRepositoryDep",
    "DocumentRepositoryDep",
    "NoteRepositoryDep",
    "ProgressRepositoryDep",
    "CatalogStorageDep",
    "MediaFilesDep",
    "get_generate_user",
    "get_restore_user",
    "get_list_formations",
    "get_get_formation",
    "get_create_formation",
    "get_rename_formation",
    "get_delete_formation",
    "get_create_chapter",
    "get_rename_chapter",
    "get_delete_chapter",
    "get_create_video",
    "get_rename_video",
    "get_delete_video",
    "get_reorder_videos",
    "get_reorder_chapters",
    "get_move_video",
    "get_list_chapter_documents",
    "get_create_document",
    "get_update_document",
    "get_delete_document",
    "get_get_video_path",
    "get_get_document_path",
    "get_reconcile_catalog",
    "get_start_media_conversion",
    "get_create_note",
    "get_list_notes",
    "get_update_note",
    "get_delete_note",
    "get_get_progress",
    "get_upsert_progress",
    "get_get_formation_progress",
    "get_list_formations_progress",
    "get_get_summary",
    "get_update_summary",
    "get_generate_summary",
    "get_start_transcription",
    "get_start_summary_generation",
    "get_start_formation_index",
    "get_get_transcription",
    "get_ask_formation",
    "get_index_formation",
]
